FROM node:22

WORKDIR /app

# Copy package files and install dependencies
COPY frontend/package*.json ./
COPY frontend/ ./

RUN npm install

# Install @quasar/cli globally after local dependencies
RUN npm install -g @quasar/cli

# Run Quasar dev server
CMD ["quasar", "dev"]