services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: go-backend
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - CGO_ENABLED=1
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - tmp/
            - .git/
        - action: rebuild
          path: ./backend/go.mod
        - action: rebuild
          path: ./backend/go.sum
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: quasar-frontend
    working_dir: /app
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=development
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
            - dist/
            - .git/
        - action: rebuild
          path: ./frontend/package.json
        - action: rebuild
          path: ./frontend/package-lock.json
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
