root = "."
tmp_dir = "tmp"
debug = true

[build]
  cmd = "go build -o tmp/main ."
  bin = ""
  full_bin = ""
  include_ext = ["go"]
  exclude_dir = ["tmp"]

[run]
  cmd = ""

[color]
  main = "yellow"

[log]
  time = true
